[Task 6 B.t.] Node.js server with network authentication. Social login
JuliaKholodetska/Task5-Full-Stack-JS-Internship pull request #10
Opened 2021-04-13 05:45 UTC by JuliaKholodetska

2021-04-14 06:57 UTC, MariiaKolisnyk requested changes

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +	googleUser: async (req, res) => {
`googleUser` is a noun, we need a verb in function names

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		throw new Error("Wrong credentials");
do you send appropriate status code the Client?

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +const registerGoogleUser = async ({ name, email }) => {
what if I as a user used my google email to sign up and then decided to sign in using Social login? and vice versa

2021-04-14 06:57 UTC, MariiaKolisnyk commented on client/src/actions/userActions.js
> +					: error.message,
- is it possible that `error.response` does not have `data` property?
- this pice of code should be unified somehow - moved to an error handler....

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +			audience: process.env.REACT_APP_GOOGLE_CLIENT_ID,
pls, update .env.example accordantly.

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		const dataUser = ticket.getPayload();
why is it `ticket`? and what if we failed to verifyIdToken?

2021-04-14 06:57 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		if (!(await User.findOne({ where: { email: dataUser.email } }))) {
pls move `await User.findOne({ where: { email: dataUser.email } })` to a constant

2021-04-14 07:24 UTC, JuliaKholodetska commented on backend/controllers/userController.js
> +		throw new Error("Wrong credentials");
yes

2021-04-14 07:24 UTC, JuliaKholodetska commented on backend/controllers/userController.js
> +const registerGoogleUser = async ({ name, email }) => {
everything works, I checked it

2021-04-14 07:24 UTC, JuliaKholodetska commented on client/src/actions/userActions.js
> +					: error.message,
i remove it

2021-04-14 07:24 UTC, JuliaKholodetska commented on backend/controllers/userController.js
> +		const dataUser = ticket.getPayload();
because LoginTicket, shows the user an error

2021-04-16 05:16 UTC, MariiaKolisnyk approved these changes
please remove comment

2021-04-16 06:24 UTC, merged