[Task 5] Database (Postgres) Connect BE with Postgres.
JuliaKholodetska/Task5-Full-Stack-JS-Internship pull request #6
Opened 2021-04-07 08:00 UTC by JuliaKholodetska

2021-04-08 10:34 UTC, MariiaKolisnyk requested changes

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +				rating: getRating(product),
I'm not sure you have to include all the properties `...product.dataValues`. please check the output. what will be the result here?

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +	}, 0);
looks like `getSum` from the previous controller. please re-use it

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +	return (await Category.findOne({ where: { name: categoryName } })).id || 0;
you can't return `0`
there is a special type in JS for this - `null` or `undefined`. since `0` can be considered as a valid `id`

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +		res.send(categories.map((category) => category.name));
why do you send just `names`? 
I do not think you need `getCategoryIdByName` if you send the whole entity

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +	getUser: expressAsyncHandler(async (req, res) => {
a single User?
why do we need this endpoint? do we have a list of users on FE?

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +	getUserDetailsById: expressAsyncHandler(async (req, res) => {
`getUser` or `getUserById`

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		}
```
if (!user) {
			// send error
		} 
 // send User
```

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +	putProfile: expressAsyncHandler(async (req, res) => {
`putProfile`: put is HTTP method, here we should use human language

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		const { name, email, password } = req.body;
at first always
```
const { name, email, password } = req.body;
```
then
```
		const user = await User.findByPk(req.user.id);
```
req.user.id - to const as well

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		if (user) {
what if not?

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +			let newUserData = {
why is it `new`? are we updating or creating a user here?

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +			const updatedUser = await User.findByPk(req.user.id);
should be done by a single request to DB

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/db/seeds/data.sql
> +>>>>>>> master
conflicts

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/models/orderItemsModel.js
> +import sequelizeDB from "../sequelize.js";
I believe this file should be removed

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/models/orderModel.js
> +	{ createdAt: false, updatedAt: false, deletedAt: false }
we always keep these fields

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/orderRouter.js
> +orderRouter.get("/mine", isAuth, orderController.getMineOrder);
no need to use `mine` in the route path

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/orderRouter.js
> +import { isAuth } from "../utils.js";
I do not like `isAuth` (does not sound like middleware), for me `ensureAuthenticated` or similar sounds better. but it's just my preference and you can leave it.
BUT `isAuth` should be place in `/middleware` folder!

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/productRouter.js
> +productRouter.get("/categories", productController.getCategories);
this should be a separate Controller

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +import { isAuth /*validate*/ } from "../utils.js";
remove a comment please

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +	/*validate(['password']),*/ userController.registerUser
please, remove a comment

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/routers/userRouter.js
> +userRouter.put("/profile", isAuth, userController.putProfile);
no need to use `profile` here

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/server.js
> +});
please, move this to `routes/index.js`. and rename you folder `routers` to `routes`

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/utils.js
> +export const isAuth = (req, res, next) => {
it's not an util

2021-04-08 10:34 UTC, MariiaKolisnyk commented on backend/utils.js
> +// }
remove comments

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/orderController.js
> +					orderItem: orderItem,
It is orderItem, we include it in Order.

Order.hasMany(OrderItem, { as: "orderItem" });
OrderItem.belongsTo(Order, {
	foreignKey: "orderId",
	as: "order",
});

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/orderController.js
> +						itemsPrice + Number(order.taxPrice) + Number(order.shippingPrice),
1. I can't do that because then it won't be in scope. 
2. I do not remember, but there was some bug with the orm, it returned string, so I prescribed the term

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/orderController.js
> +			const updatedOrder = await Order.findByPk(req.params.id, {
now it is used only one time.

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/productController.js
> +			order: [sortOrder],
I'll think about it later

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/productController.js
> +				.sort((a, b) =>
sorry I didn't find a way to transfer it to orm.

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/productController.js
> +		res.send(categories.map((category) => category.name));
I have to pass the parameter here.

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/controllers/userController.js
> +			const updatedUser = await User.findByPk(req.user.id);
sorry can't solve it.

2021-04-08 15:48 UTC, JuliaKholodetska commented on backend/models/orderModel.js
> +	{ createdAt: false, updatedAt: false, deletedAt: false }
ok, I'll know, I don't want to re-create the database now, so if I can I'll leave it like this, pls.

2021-04-08 15:52 UTC, JuliaKholodetska commented on backend/controllers/orderController.js
> +		if (orderItem.length === 0) {
ok

2021-04-09 12:52 UTC, MariiaKolisnyk commented on backend/controllers/orderController.js
> +					orderItem: orderItem,
I do not see order items were created. I can be mistaken

2021-04-09 12:52 UTC, MariiaKolisnyk commented on backend/controllers/orderController.js
> +const Create = (order, itemsPrice) => {
I must have missed this...
this is not `Create` but rather `formatOrderResponse`

2021-04-09 12:52 UTC, MariiaKolisnyk commented on backend/controllers/orderController.js
> +						itemsPrice + Number(order.taxPrice) + Number(order.shippingPrice),
1. you can do everything you want. at least you could have moved it to a const and used `Number` once
2. I don't believe in it. if you have `integer` type in DB you should be able to use it as integer

2021-04-09 13:19 UTC, MariiaKolisnyk requested changes

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +			: {};
too complicated. you should provide `categoryId` to the Client so the Client will be able to give you `categoryId`

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/categoryController.js
> +		res.send(categories.map((category) => category.name));
I do think the Client needs `id` as well

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +				"brand.id",
do we really need all this list here?

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +
pls, remove an empty line

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +		if (product) {
```
if (!product) { 
// send an error 
} 
// do stuff
```

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +		res.send(categories.map((category) => category.name));
which parameter? you have to send at least name and id to the Client but not just name

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +const ratingall = Rating.findAll({
`ratingall` - there is no such a word, pls use camel case

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +const ratingall = Rating.findAll({
why do we need this method?

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +	return getSum(ratings);
this sum of all the rating? should not it be an average value?

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +	profile: async (req, res) => {
the method should be renamed, I do not understand what it does from its name

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		//const { id } = req.user;
pls, uncomment and use this const

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/controllers/userController.js
> +		if (user) {
anything here??

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/models/orderItemsModel.js
> +import sequelizeDB from "../sequelize.js";
why do you have `OrderItem` models??

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/routes/index.js
> +});
actually, there should be only routes here

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/server.js
> -import express from "express";
this file should be reverted

2021-04-09 13:19 UTC, MariiaKolisnyk commented on backend/routes/index.js
> +});
tip - take a look at `express.Router()`

2021-04-09 16:46 UTC, JuliaKholodetska commented on backend/controllers/productController.js
> +			: {};
why?
i believe its okey

2021-04-09 16:46 UTC, JuliaKholodetska commented on backend/controllers/categoryController.js
> +		res.send(categories.map((category) => category.name));
i think it's ok

2021-04-09 16:47 UTC, JuliaKholodetska commented on backend/controllers/productController.js
> +const ratingall = Rating.findAll({
forgot to delete it, sorry.

2021-04-10 12:33 UTC, MariiaKolisnyk requested changes

2021-04-10 12:33 UTC, MariiaKolisnyk commented on backend/routes/index.js
> +export default appRoute;
please study the best routing practices and update your code according to them. 
an example:
https://scotch.io/tutorials/keeping-api-routing-clean-using-express-routers

2021-04-10 12:33 UTC, MariiaKolisnyk commented on backend/controllers/orderController.js
> +			});
since you have all the needed data in order you should pass it to `formatOrderResponse` and do calculation there
Please move `const itemsPrice = getSum....` to `formatOrderResponse`

2021-04-10 12:33 UTC, MariiaKolisnyk commented on backend/controllers/orderController.js
> +};
this is odd if you get integer type as strings... could you please show me what exactly you get here for `shippingPrice` & `taxPrice`?

2021-04-10 21:05 UTC, JuliaKholodetska commented on backend/controllers/userController.js
> +					id: updatedUser.dataValues,
yes

2021-04-10 21:05 UTC, JuliaKholodetska commented on backend/controllers/orderController.js
> +};
I remove it because I already get a number, not a string here.

As for the category, I do not ignore the comments, I just need names there and just such a construction, so I would like to leave as is, without id.

And about "please, create a ticket for this." I already had such a ticket.

2021-04-12 08:09 UTC, MariiaKolisnyk requested changes

2021-04-12 08:09 UTC, MariiaKolisnyk commented on backend/routes/orderRouter.js
> +	"/user/order",
`userOrderList`

2021-04-12 12:15 UTC, MariiaKolisnyk approved these changes
you can merge after fixing a small comment. huge PR and great work here!

2021-04-12 12:15 UTC, MariiaKolisnyk commented on backend/controllers/productController.js
> +		let categoryFilter;
I think you should init the variable since in case if `category = 'all'` you will have
```
where: {
				...nameFilter,
				...UNDEFINED,
				...priceFilter,
				...ratingFilter,
			},
```

2021-04-12 15:06 UTC, merged