[Task 5] Database (Postgres). Validation.
JuliaKholodetska/Task5-Full-Stack-JS-Internship pull request #9
Opened 2021-04-12 15:13 UTC by JuliaKholodetska

2021-04-13 07:04 UTC, MariiaKolisnyk requested changes
I suggest using a validator package, e.g. https://express-validator.github.io/docs/

Please check schema for all the routes which need it (example - https://express-validator.github.io/docs/schema-validation.html)

2021-04-14 06:36 UTC, MariiaKolisnyk approved these changes

2021-04-14 06:36 UTC, MariiaKolisnyk commented on backend/middleware/validator.js
> +		return res.status(400).send({ message: "Invalid email or password" });
I would use another error message as here we only validate them. message 'Invalid email or password' sounds like the input is correct but we do not match a user for it.
smth like - `Validation error`. for advanced level we even can pass to the Client which exactly we don't like (e.g. password should be at least 7 characters long)

2021-04-14 07:03 UTC, JuliaKholodetska commented on backend/middleware/validator.js
> +		return res.status(400).send({ message: "Invalid email or password" });
I update it.

2021-04-15 06:23 UTC, MariiaKolisnyk requested changes

2021-04-15 06:23 UTC, MariiaKolisnyk commented on backend/middleware/validator.js
> +			.send({ message: "Password should be at least 7 characters long." });
oh, I meant `advanced` level which means a bit more effort from your side - https://express-validator.github.io/docs/custom-error-messages.html
in this case you will always send `Password should be at least 7 characters long.` even if there is an error for emal or name.

2021-04-16 05:13 UTC, MariiaKolisnyk approved these changes

2021-04-16 06:16 UTC, merged